### ISSUE TITLE
【功能增强】泛收件人的设置

### ISSUE THREAD

**Issue by addpromax** [MrXiaoM/SweetMail#2]
泛收件人建议在增加：
未来xx天内上线的所有玩家（用来发节日礼物 比如七夕节礼物是8.9-8.11之间可以领取的这种）没在期间上线就不会收到
最好是支持日期就好了

**Comment by MrXiaoM** [comment]
这样的话得把定时发送也写了

**Comment by addpromax** [comment]
市面上倒是没有支持的 所以我觉得很有必要

**Comment by addpromax** [comment]
此外 最好给管理员高级配置里边添加一个指令执行 这样给游戏币的方便

**Comment by MrXiaoM** [comment]
附件里面已经有金币附件和后台命令附件了，添加附件菜单还没写，目前只能添加物品附件

**Comment by addpromax** [comment]
好

**Comment by MrXiaoM** [comment]
定时发送 和 泛收件人设置玩家上线时间区间 写好了，还没写界面，写高级设置的时候再统一写。
暂时不打算开放定时发送给玩家使用，取消起来麻烦

**Comment by addpromax** [comment]
没必要给玩家 管理员专用就够了
此外期待快点完成高级设置（）

**Comment by MrXiaoM** [comment]
暂定高级设置的界面如下
```yaml
items:
  系:
    material: NAME_TAG
    display: '&e&l发件人显示名称'
    lore:
      - ''
      - '  &f自定义发件人显示名称，'
      - '  &f使得邮件发送时变为&e系统邮件。'
      - '  &f设置此项后发送邮件，邮件将不会'
      - '  &f出现在你的发件箱中。'
      - ''
      - '  &f当前: %sender%'
      - ''
      - '&a左键&7 | &f设置发件人显示名称'
      - '&b右键&7 | &f移除发件人显示名称'
  收:
    material: CHEST
    display: '&e&l泛收件人选项'
    lore:
      - ''
      - '  &f使得所有满足条件的玩家'
      - '  &f都能收到这封邮件。当前表达式:'
      - '  &e%receiver%'
      - ''
      - '&a鼠标悬停并按下数字键进行设置'
      - '&b1 &7| &f当前服区在线玩家'
      - '&b2 &7| &f全服(BungeeCord)在线玩家'
      - '&b3 &7| &f在多久之前到现在，上过线的玩家'
      - '&b4 &7| &f在某段时间内上过线的玩家'
    prompts:
      3:
        tips: '&7[&e&l邮件&7] &b请在聊天栏发送，&f“多久之前到现在，上过线的玩家”&b的 &e判定起始时间 &7(格式 &f年-月-日 时:分:秒&7，不输入时分秒部分默认为0。输入 &ccancel &7取消设置)'
        cancel: 'cancel'
      4:
        tips-start: '&7[&e&l邮件&7] &b请在聊天栏发送，&f“在某段时间内上过线的玩家”&b的 &e判定起始时间 &7(格式 &f年-月-日 时:分:秒&7，不输入时分秒部分默认为0。输入 &ccancel &7取消设置)'
        tips-end: '&7[&e&l邮件&7] &b请在聊天栏发送，&f“在某段时间内上过线的玩家”&b的 &e判定结束时间 &7(格式 &f年-月-日 时:分:秒&7，不输入时分秒部分默认为0。输入 &ccancel &7取消设置)'
        cancel: 'cancel'
  定:
    material: CLOCK
    display: '&a&l定时发送'
    lore:
      - ''
      - '  &f将这份草稿加入定时发送队列'
      - '  &f并删除这个草稿'
      - '  &c注意，这不是一个设置!'
      - '  &c设置时间后邮件立即加入队列等待发送!'
      - ''
      - '&a左键 &7| &f设置定时发送'
      - '&b右键 &7| &f使用泛收件人表达式'
      - '&f  last played from (如果有)'
      - '&f  的结束时间设置定时发送'
  返:
    material: RED_DYE
    display: '&e&l返回'
    lore:
      - ''
      - '&a左键&7 | &f回到草稿编辑器'
```
