### ISSUE TITLE
关于邮件发送方面的建议~~

### ISSUE THREAD

**Issue by Yuze12** [MrXiaoM/SweetMail#28]
目前发送邮件的方式只有手动用草稿方式发送邮件，针对系统自动发件的方式只有开发接口!如果想实现自动发件的话门槛太高了555，没办法单独依赖这个完美的邮箱插件实现各种发件需求。
我观察到存储在插件目录里的草稿箱格式非常完整。
可不可以像草稿箱一样，在插件目录里新增一个文件夹来放置预设好的邮件
通过指令比如：
`/sweetmail 预设邮件 <预设邮件名称>`
来打开像草稿箱一样的编辑界面来设定一个邮件模板存储到插件预设目录里完成一次邮件模板存储，编辑界面移除掉收件人和泛收件人选项。
之后通过指令：
`/sweetmail <玩家名/泛收件人选项> <预设邮件名称>`
来调用预设好的邮件自动完成发送呢! 这样就可以使用一条简单的指令实现发送邮件功能了不需要每个邮件都手动编辑!!

这样的话应该也不会需要改动太多的代码!也能使得插件更加完善!!（开发接口不会用555）
如果可以实现的话这个插件完整度将会得到史诗级的提升!！

**Comment by Yuze12** [comment]
怎么会有这么多删除线az  我重新编辑一下

**Comment by Yuze12** [comment]
目前发送邮件的方式只有手动用草稿方式发送邮件，针对系统自动发件的方式只有开发接口~如果想实现自动发件的话门槛太高了555，没办法单独依赖这个完美的邮箱插件实现各种发件需求。
我观察到存储在插件目录里的草稿箱格式非常完整。
可不可以像草稿箱一样，在插件目录里新增一个文件夹来放置预设好的邮件
通过指令比如：
`/sweetmail 预设邮件 <预设邮件名称>`
来打开像草稿箱一样的编辑界面来设定一个邮件模板存储到插件预设目录里完成一次邮件模板存储，编辑界面移除掉收件人和泛收件人选项。
之后通过指令：
`/sweetmail <玩家名/泛收件人选项> <预设邮件名称>`
来调用预设好的邮件自动完成发送呢~ 这样就可以使用一条简单的指令实现发送邮件功能了不需要每个邮件都手动编辑~~

这样的话应该也不会需要改动太多的代码~也能使得插件更加完善~~（开发接口不会用555）
如果可以实现的话这个插件完整度将会得到史诗级的提升~！

**Comment by MrXiaoM** [comment]
`~~` 是 markdown 的删除线语法

**Comment by Yuze12** [comment]
> `~~` 是 markdown 的删除线语法

谢谢提醒哈哈，已经重新编辑了

**Comment by MrXiaoM** [comment]
MB 有人私信我建议添加邮件模板功能了，在写，不会这么快完成
```yaml
    - '  &f/mail send <模板> <玩家> [参数...] &8-- &e根据已配置的模板发送邮件'
``` 

```yaml
# 变量配置
# 可以在邮件配置中使用 ${变量名} 的方式使用这里的变量
# 变量通过命令输入，你也可以为变量设置默认值，使得某个变量可选
# 当命令中没有输入某个无默认值变量时，发送邮件将会提示报错
variables:
  # 变量名，用法 ${money}
  money:
    # 变量类型，必选，可用以下值
    # string - 字符串
    # number - 实数
    # integer - 整数
    type: number
    # 默认值，可选
    default: 100

# 邮件配置
mail:
  # 发件人显示名称
  sender: '系统消息'
  # 邮件图标
  icon: PAPER
  # 邮件标题
  title: '示例邮件'
  # 邮件正文
  contents:
    # 这里的名字随便取
    # 插件不会读取数字，会按顺序添加页面
    1:
      - '第一页'
    随便_不重复就行:
      - '第二页'
  # 邮件附件
  attachments:
    - 'money:${money}'
  # 邮件到期时间，0 或 infinite 为永久有效
  outdate-time: 7d

```
