### ISSUE TITLE
允许配置未读和已读邮件的物品和cmd

### ISSUE THREAD

**Issue by addpromax** [MrXiaoM/SweetMail#39]
如题

**Comment by MrXiaoM** [comment]
请给出确切可行、可兼容自定义邮件图标的方案

**Comment by addpromax** [comment]
就是未读和已读可以配置物品和custommodeldata？
现在不是一张纸吗 不能操作吗 我也不是很熟悉 你能具体说说吗？

**Comment by MrXiaoM** [comment]
你的提问不明确，可以同时指代
+ 收件箱、发件箱界面左侧的操作按钮
+ 邮件项目图标

**Comment by addpromax** [comment]
哦哦 我是指的邮件项目图标

![Image](https://github.com/user-attachments/assets/ddc9e609-bab1-4c9d-8d13-08c3f9eef66d)

**Comment by MrXiaoM** [comment]
如果你要改未读状态和已读状态的图标，这个东西你要怎么兼容？
```yaml
# 预设图标，不能写 custom，不能以英文感叹号开头
preset-icons:
  # default 为默认图标，必须要有默认图标
  default:
    display: '默认'
    item: BUNDLE
  example:
    display: '示例1'
    # 使用 MythicMobs 物品作为图标 (草稿菜单显示mm物品名，收件箱发件箱中仅使用物品、CustomModelData、附魔、染色数据，不使用名字和 Lore)
    item: mythic-示例
  example1:
    display: '示例2'
    # 使用 ItemsAdder 物品作为图标，显示策略同 MythicMobs 图标
    item: itemsadder-示例
```
